version: "3"

services:
  krakend-design:
    image: devopsfaith/krakendesigner:latest
    ports:
      - "8081:80"
    networks:
      - onefence
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ../krakend:/etc/krakend
    ports:
      - "8080:8080"
    networks:
      - onefence

networks:
  onefence: