version: "3.9"

networks:
  onefence:

services:
  users:
    build:
      dockerfile: Dockerfile-go
      context: .
      target: dev
    environment:
      service_path: services/users
    volumes:
      - ../..:/onefence
    networks:
      - onefence
  users-dapr:
    image: daprio/daprd:edge
    command:
      [
          "./daprd",
          "-app-id",
          "users",
          "-app-port",
          "4000",
          "-placement-host-address",
          "placement:50006",
          "-config",
          "/configurations/tracing.yaml",
      ]
    volumes:
      - "../dapr/:/configurations"
    depends_on:
      - nodeapp
    network_mode: "service:users"
