version: "3.9"

networks:
  onefence:

services:
  publish:
    build:
      dockerfile: Dockerfile-go
      context: .
      target: dev
    environment:
      service_path: services/publish
    volumes:
      - ../..:/onefence
    networks:
      - onefence
  publish-dapr:
    image: daprio/daprd:edge
    command:
      [
          "./daprd",
          "-app-id",
          "publish",
          "-placement-host-address",
          "placement:50006",
          "-config",
          "/configurations/config.yml",
          "-components-path",
          "/configurations/components"
      ]
    volumes:
      - "../dapr/:/configurations"
    depends_on:
      - publish
    network_mode: "service:publish"
